// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkJ2j2XDu55piseC5Osv8e-MYhlOhyJA',
    appId: '1:413381307204:web:ddf6c9b341af621e574511',
    messagingSenderId: '413381307204',
    projectId: 'whatsapp-z-1d359',
    authDomain: 'whatsapp-z-1d359.firebaseapp.com',
    storageBucket: 'whatsapp-z-1d359.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxWoipXMnCZfUZnZKhFMAIJ7mKWCp-UMs',
    appId: '1:413381307204:android:372aedc914b371ff574511',
    messagingSenderId: '413381307204',
    projectId: 'whatsapp-z-1d359',
    storageBucket: 'whatsapp-z-1d359.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ai8pE8A2FasAX245NjsPVmZc7BXZVGg',
    appId: '1:413381307204:ios:39a78b0e1d7f855a574511',
    messagingSenderId: '413381307204',
    projectId: 'whatsapp-z-1d359',
    storageBucket: 'whatsapp-z-1d359.appspot.com',
    iosBundleId: 'com.example.whatsappMsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ai8pE8A2FasAX245NjsPVmZc7BXZVGg',
    appId: '1:413381307204:ios:39a78b0e1d7f855a574511',
    messagingSenderId: '413381307204',
    projectId: 'whatsapp-z-1d359',
    storageBucket: 'whatsapp-z-1d359.appspot.com',
    iosBundleId: 'com.example.whatsappMsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjkJ2j2XDu55piseC5Osv8e-MYhlOhyJA',
    appId: '1:413381307204:web:38ca6ec2dd8f3bdc574511',
    messagingSenderId: '413381307204',
    projectId: 'whatsapp-z-1d359',
    authDomain: 'whatsapp-z-1d359.firebaseapp.com',
    storageBucket: 'whatsapp-z-1d359.appspot.com',
  );
}
